name: Destroy the AWS Ec2 infrastructure.
run-name: Destroy EC2
on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: Destroy AWS Ec2 Infrastructure
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: 1.10.3

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"

    - name: remove terraform cache Terraform Init
      run: |
       rm -rf .terraform/
       terraform init
      
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
